apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-persistent-volume-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
