apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-persistent-volume
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/jenkins