apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-persistent-volume
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/registry/
