master:
  ingress:
    enabled: true
    path: /
    annotations:
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/secure-backends: "true"

persistence:
  existingClaim: jenkins-persistent-volume-claim