controller:
  ingressClass: nginx

  resources: 
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 256Mi

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 75
    targetMemoryUtilizationPercentage: 80

  metrics:
    enabled: true

  defaultBackendService: true

defaultBackend:
  enabled: true

rbac:
  create: true