controller:
  ingressClass: nginx
  hostNetwork: true
  kind: DaemonSet
  
  service:
    type: ""

  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 96Mi

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 90
    targetMemoryUtilizationPercentage: 90

  metrics:
    enabled: true

  defaultBackendService: true

defaultBackend:
  enabled: true

rbac:
  create: true